name: Run Prediction Script

on:
  push:
    branches:
      - main  # Runs on any push to the main branch

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn matplotlib openpyxl

    # Step 4: Run the Python script
    - name: Run prediction script
      run: |
        python src/prediction_script.py

    # Step 5: Upload the generated artifact (prediction plot)
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: prediction-plot
        path: artifacts/prediction_plot.png
